% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Applied Research: Advance Statistics with R},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Applied Research: Advance Statistics with R}
\author{true}
\date{6/08/2020}

\begin{document}
\maketitle

\begin{figure}
\centering
\includegraphics{https://maastrichtu-ids.github.io/AppliedRR/pics/logo\%20campus.jpg}
\caption{While}
\end{figure}

\hypertarget{welcome}{%
\section{WELCOME}\label{welcome}}

Welcome to the \textbf{workshop number 3: Introduction to inferential
stats with R.}

\hypertarget{learning-outcomes}{%
\subsection{Learning outcomes:}\label{learning-outcomes}}

By the end of this assignment(s), you should be able to:

\begin{itemize}
\item
  Formulate different hypothesis testing
\item
  Interpret hypothesis testing model outputs
\item
  Calculate correlation and covariance
\item
  Interpret pearson correlation and scatter plots
\item
  Loop functions in R (bonus exercise)
\end{itemize}

\hypertarget{essential-r-assignments-document-guidelines}{%
\subsubsection{Essential R assignment(s) document
guidelines:}\label{essential-r-assignments-document-guidelines}}

In the current document you will find the following color(s)
highlight(s) and format(s). Please refer to this table for legend
description.

\hypertarget{dataset}{%
\subsubsection{Dataset}\label{dataset}}

In this assignment(s), we will use the following dataset: 1. Workshop
Statistics\_ descriptives .xlsx.

\hypertarget{quick-started-with-hyptohesis-testing}{%
\paragraph{Quick started with hyptohesis
testing}\label{quick-started-with-hyptohesis-testing}}

Statisticians use hypothesis testing to formally check whether the
hypothesis is accepted or rejected. Hypothesis testing refers to the
process of generating a clear and testable question, collecting and
analyzing appropriate data, and drawing an inference that answers your
question. Of course, this means that some steps come into play.
Generally speaking, hypothesis testing is conducted in the following
manner:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.33}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.33}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.33}}@{}}
\toprule
Phase & Definition & Explanation \\
\midrule
\endhead
Phase 1 & State the hypotheses & Stating the null and alternative
hypotheses \\
Phase 2 & Formulate the analysis Plan & The selection of the statistical
procedure is crucial \\
Phase 3 & Analyze sample data & Calculation and interpretation of the
test statistics \\
Phase 4 & Interpret results & Application of the decision rules \\
\bottomrule
\end{longtable}

\textbf{By hand procedure}:

\_Suppose the mean weight of
\href{https://en.wikipedia.org/wiki/Alpaca}{baby alpacas} found in an
\href{https://en.wikipedia.org/wiki/Cusco}{Cusco} (Peru) last year was
15.4 kg.

In a sample of 35 baby alpacas same time this year in the same town, the
mean baby alpacas weight is 14.6 kg. Assume the sample standard
deviation is 2.5 kg. At .05 significance level, can we reject the null
hypothesis that the mean baby alpacas weight does not differ from last
year?\_

\textbf{Calculation}:

The null hypothesis is that μ = 15.4. We begin with computing the test
statistic:

\begin{verbatim}
## [1] -1.893146
\end{verbatim}

Here is:

\texttt{xbar}: Sample mean \texttt{mu0}: Hypothesized value
\texttt{sig}: Standard deviation of sample \texttt{n}: Sample size
\texttt{t}: Test statistics

We then compute the critical values at .05 significance level. You can
compute the tα/2,n−p critical value in R by doing qt(1-alpha/2, n-p).

\begin{verbatim}
## [1] -2.032245  2.032245
\end{verbatim}

\hypertarget{answer}{%
\paragraph{Answer:}\label{answer}}

\emph{Critical boundaries}:

The test statistic -1.8931 lies between the critical values -2.0322, and
2.0322. Hence, at .05 significance level, we do not reject the null
hypothesis that the mean penguin weight does not differ from last year

\emph{p-value}:

Instead of using the critical value, we apply the pt function to compute
the two-tailed p-value of the test statistic. It doubles the lower tail
p-value as the sample mean is less than the hypothesized value. Since it
turns out to be greater than the .05 significance level, we do not
reject the null hypothesis that μ = 15.4.

\begin{verbatim}
## [1] 0.06687552
\end{verbatim}

We have seen an \emph{hand procedure of hypothesis testing} with the
intuitive `critical value'and 'p-value' decision making approach. Now,
we are going to use R functions in order automatically calculate such
statistics.

If you want to get more familiar with the hand procedure of hypothesis
testing, you have a look in the following tutorials: -
\url{http://www.r-tutor.com/elementary-statistics/hypothesis-testing} -
\href{\%5Bhttps://www.youtube.com/watch?v=yvHQEJnYZBY\%5D}{Hypothesis
Testing by Hand: A Single Sample tTest}

\hypertarget{using-the-students-t-test}{%
\subsubsection{Using the Student's
T-test}\label{using-the-students-t-test}}

R can handle the various versions of T-test using the \texttt{t.test()}
command. This function can be used to deal with one-sample tests as well
as two-sample (un-)paired tests.

\hypertarget{unparied-independent-samples-t-test}{%
\subsubsection{(Unparied) Independent samples
t-test}\label{unparied-independent-samples-t-test}}

The independent sample t-test compares the mean of one distinct group to
the mean of another group. An example research question for an
independent sample t-test would be, ``Do boys and girls differ in their
age expectancy?''

Independent t-test or (unpaired t-test) is used to compare the means of
two unrelated groups of samples. The aim of this section is to show you
how to calculate independent samples t test with R software. The t-test
formula is described
\href{http://www.sthda.com/english/wiki/t-test-formula}{here}.

In the lecture, we conducted a experiment in order to investigate
weather or not `coffee lovers' shops pounder 33 cl on the orange juice.
In our experiment we collected data of 10 orange juices and measured
amount of orange cl per glass. The results are here:

\begin{longtable}[]{@{}ll@{}}
\toprule
id & cl \\
\midrule
\endhead
1 & 28 \\
2 & 31 \\
3 & 28 \\
4 & 37 \\
5 & 30 \\
6 & 33 \\
7 & 25 \\
8 & 33 \\
9 & 24 \\
10 & 30 \\
\bottomrule
\end{longtable}

Let's create the hypothesis null for `two-sides' in R as following:

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  orange_maastricht and orange_amsterdam
## t = 0.51925, df = 18, p-value = 0.6099
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.046056  5.046056
## sample estimates:
## mean of x mean of y 
##      29.9      28.9
\end{verbatim}

\emph{Model output description}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.26}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.74}}@{}}
\toprule
variable & description \\
\midrule
\endhead
\texttt{title} & Type of test performed. \\
\texttt{t} & t statistic. \\
\texttt{df} & degrees of freedom --- sample size - 1. \\
\texttt{p-value} & probability of selecting a sample with mean not equal
to 33 cl. \\
\texttt{Ha} & Alternative hypothesis \\
\texttt{C.I\ 95\%} & indicates that 95\% of all hpothetical samples one
could drawn a conclusion. \\
\texttt{upper-lower} & this boudaries give and indication of most likely
values. \\
\bottomrule
\end{longtable}

\emph{Model output interpretation}

From the model output, we can see that the mean orange volume in cl for
the sample is 29.9 cl. The two-sided 95\% confiance interval tells you
that the mean orange volume is likely to be between 27.11 and 32.6 cl.
The p-value of 0.033 tells you if the mean volume of orange juice were
33 cl, the probability to select a sample with a mean volume not equal
to 33 cl would be approximately 3\% (p-value = 0.033). Since the p-value
is less than the significance level (0.05), we can reject the true mean
is equal to 33 cl. This means that there is not statistical evidence
that orange juice are being equal to 33 cl.

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{verbatim}
## # A tibble: 1 x 1
##   Avg_Life_SouthAfrica
##                  <dbl>
## 1                 54.0
\end{verbatim}

\begin{verbatim}
## # A tibble: 1 x 1
##   Avg_Life_Ireland
##              <dbl>
## 1             73.0
\end{verbatim}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  lifeExp by country
## t = 10.067, df = 19.109, p-value = 4.466e-09
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  15.07022 22.97794
## sample estimates:
##      mean in group Ireland mean in group South Africa 
##                   73.01725                   53.99317
\end{verbatim}

\hypertarget{scatter-plot-correlation-and-covariance}{%
\subsection{Scatter plot, correlation and
covariance}\label{scatter-plot-correlation-and-covariance}}

In statistics, you deal with a lot of data. The hard part is finding
patterns that fit the data. To look for patterns, there are several
statistical tools that help identify these patterns. But before you use
any of these tools, you should look for basic patterns. As you learned,
you can identify basic patterns using a scatter plot and correlation.

Let's create a simple scatter plot:

\includegraphics{intro-infer-R_files/figure-latex/unnamed-chunk-8-1.pdf}
According to this figure, we might conclude that there is a weak
association between age and length variables. Also, we cannot clearly
define the direction of this association. Relying on the interpretation
of a scatterplot is too subjective. More precise evidence is needed, and
this evidence is obtained by computing a coefficient that measures the
strength of the relationship under investigation.

\includegraphics{intro-infer-R_files/figure-latex/unnamed-chunk-9-1.pdf}

You could see from the scatter plot that including this line, add more
information about the slope/direction of the relationship.

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.0.5
\end{verbatim}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{intro-infer-R_files/figure-latex/unnamed-chunk-10-1.pdf}

\end{document}
